services:
  - type: web
    name: opportunitydash
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://avenir:13Avenir2025%40@avenirapproval.irpnuud.mongodb.net/opportunity-dashboard
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://opportunitydash.onrender.com/api
